In [1]:
import pandas as pd

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
os.chdir('C:/Users/basleal/Desktop/tutorial/kaim-week-7')
print(os.getcwd())

C:\Users\basleal\Desktop\tutorial\kaim-week-7

In [5]:
path = 'C:/Users/basleal/Desktop/tutorial/kaim-week-7/data/telegram_data.csv'
data = pd.read_csv(path)
data

,Channel Title,Channel Username,ID,Message,Date,Media Path
0,Doctors Ethiopia,https://t.me/DoctorsET,864,https://youtu.be/5DBoEm-8kmA?si=LDLuEecNfULJVD...,2023-12-18 17:04:02+00:00,NaN
1,Doctors Ethiopia,https://t.me/DoctorsET,863,ዶክተርስ ኢትዮጵያ በ አዲስ አቀራረብ በ ቴሌቪዥን ፕሮግራሙን ለመጀመር ከ...,2023-11-03 16:14:39+00:00,NaN
2,Doctors Ethiopia,https://t.me/DoctorsET,862,ሞት በስኳር \n\nለልጆቻችን የምናሲዘው ምሳቃ ሳናቀው እድሚያቸውን ይቀን...,2023-10-02 16:37:39+00:00,NaN
3,Doctors Ethiopia,https://t.me/DoctorsET,861,ከ HIV የተፈወሰ ሰው አጋጥሟችሁ ያቃል ? ፈውስ እና ህክምና ?\n\nሙ...,2023-09-16 07:54:32+00:00,NaN
4,Doctors Ethiopia,https://t.me/DoctorsET,860,በቅርብ ጊዜ በሃገራችን ላይ እየተስተዋለ ያለ የተመሳሳይ ፆታ ( Homos...,2023-09-01 16:16:15+00:00,NaN
...,...,...,...,...,...,...
6424,ETHIO-AMERICAN MEDICAL TRAININGS( CPD ) & HEAL...,https://t.me/EAHCI,8,አማራ ክልል ባህር_ዳር \n -------------------------...,2021-04-01 15:19:59+00:00,NaN
6425,ETHIO-AMERICAN MEDICAL TRAININGS( CPD ) & HEAL...,https://t.me/EAHCI,4,NaN,2021-03-31 19:37:59+00:00,NaN
6426,ETHIO-AMERICAN MEDICAL TRAININGS( CPD ) & HEAL...,https://t.me/EAHCI,3,NaN,2021-03-31 19:20:22+00:00,NaN
6427,ETHIO-AMERICAN MEDICAL TRAININGS( CPD ) & HEAL...,https://t.me/EAHCI,2,NaN,2021-03-31 19:11:28+00:00,NaN
6428,ETHIO-AMERICAN MEDICAL TRAININGS( CPD ) & HEAL...,https://t.me/EAHCI,1,NaN,2021-03-31 19:00:32+00:00,NaN

In [6]:
data.isnull().sum()

Channel Title          0
Channel Username       0
ID                     0
Message             1243
Date                   0
Media Path          6429
dtype: int64

In [10]:
from scripts.data_cleaning import data_cleaner
cleaned_data=data_cleaner(data)
cleaned_data

,Channel Title,Channel Username,ID,Message,Date,Media Path
0,doctors ethiopia,https://t.me/DoctorsET,864,https://youtu.be/5DBoEm-8kmA?si=LDLuEecNfULJVD...,2023-12-18 17:04:02+00:00,NaN
1,doctors ethiopia,https://t.me/DoctorsET,863,ዶክተርስ ኢትዮጵያ በ አዲስ አቀራረብ በ ቴሌቪዥን ፕሮግራሙን ለመጀመር ከ...,2023-11-03 16:14:39+00:00,NaN
2,doctors ethiopia,https://t.me/DoctorsET,862,ሞት በስኳር \n\nለልጆቻችን የምናሲዘው ምሳቃ ሳናቀው እድሚያቸውን ይቀን...,2023-10-02 16:37:39+00:00,NaN
3,doctors ethiopia,https://t.me/DoctorsET,861,ከ HIV የተፈወሰ ሰው አጋጥሟችሁ ያቃል ? ፈውስ እና ህክምና ?\n\nሙ...,2023-09-16 07:54:32+00:00,NaN
4,doctors ethiopia,https://t.me/DoctorsET,860,በቅርብ ጊዜ በሃገራችን ላይ እየተስተዋለ ያለ የተመሳሳይ ፆታ ( Homos...,2023-09-01 16:16:15+00:00,NaN
...,...,...,...,...,...,...
6424,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,8,አማራ ክልል ባህር_ዳር \n -------------------------...,2021-04-01 15:19:59+00:00,NaN
6425,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,4,NaN,2021-03-31 19:37:59+00:00,NaN
6426,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,3,NaN,2021-03-31 19:20:22+00:00,NaN
6427,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,2,NaN,2021-03-31 19:11:28+00:00,NaN
6428,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,1,NaN,2021-03-31 19:00:32+00:00,NaN

In [14]:
from scripts.data_cleaning import data_validation
validated_data=data_validation(cleaned_data)
validated_data

 Data validation complete

(Empty DataFrame
 Columns: [Channel Title, Channel Username, ID, Message, Date, Media Path]
 Index: [],
 None)

In [13]:
cleaned_data

,Channel Title,Channel Username,ID,Message,Date,Media Path
0,doctors ethiopia,https://t.me/DoctorsET,864,https://youtu.be/5DBoEm-8kmA?si=LDLuEecNfULJVD...,2023-12-18 17:04:02+00:00,NaN
1,doctors ethiopia,https://t.me/DoctorsET,863,ዶክተርስ ኢትዮጵያ በ አዲስ አቀራረብ በ ቴሌቪዥን ፕሮግራሙን ለመጀመር ከ...,2023-11-03 16:14:39+00:00,NaN
2,doctors ethiopia,https://t.me/DoctorsET,862,ሞት በስኳር \n\nለልጆቻችን የምናሲዘው ምሳቃ ሳናቀው እድሚያቸውን ይቀን...,2023-10-02 16:37:39+00:00,NaN
3,doctors ethiopia,https://t.me/DoctorsET,861,ከ HIV የተፈወሰ ሰው አጋጥሟችሁ ያቃል ? ፈውስ እና ህክምና ?\n\nሙ...,2023-09-16 07:54:32+00:00,NaN
4,doctors ethiopia,https://t.me/DoctorsET,860,በቅርብ ጊዜ በሃገራችን ላይ እየተስተዋለ ያለ የተመሳሳይ ፆታ ( Homos...,2023-09-01 16:16:15+00:00,NaN
...,...,...,...,...,...,...
6424,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,8,አማራ ክልል ባህር_ዳር \n -------------------------...,2021-04-01 15:19:59+00:00,NaN
6425,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,4,NaN,2021-03-31 19:37:59+00:00,NaN
6426,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,3,NaN,2021-03-31 19:20:22+00:00,NaN
6427,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,2,NaN,2021-03-31 19:11:28+00:00,NaN
6428,ethio-american medical trainings( cpd ) & heal...,https://t.me/EAHCI,1,NaN,2021-03-31 19:00:32+00:00,NaN

In [15]:
cleaned_data.to_csv('cleaned_data.csv')